// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v3.21.12
// source: song.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "song";

export interface Song {
  id: string;
  title: string;
}

export interface GetSongsRequest {
}

export interface GetSongsResponse {
  song: Song[];
}

export const SONG_PACKAGE_NAME = "song";

export interface SongServiceClient {
  getSongs(request: GetSongsRequest): Observable<GetSongsResponse>;
}

export interface SongServiceController {
  getSongs(request: GetSongsRequest): Promise<GetSongsResponse> | Observable<GetSongsResponse> | GetSongsResponse;
}

export function SongServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getSongs"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("SongService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("SongService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const SONG_SERVICE_NAME = "SongService";
